spring:
  application:
    name: driver-service
  datasource:
    url: jdbc:postgresql://localhost:5432/logistics_db
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        ddl-auto: update
        jdbc:
          time_zone: Asia/Kolkata
    show-sql: false
  kafka:
    bootstrap-servers: localhost:9092

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: driver-group
      auto-offset-reset: latest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: com.upskill.smart.kafka.events

server:
  port: 8082
